/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MySider: typeof import('./src/components/sider/index.vue')['default']
    PageTransition: typeof import('./src/components/pageTransition/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/sider/index.vue')['default']
    Stable: typeof import('./src/components/Stable/index.vue')['default']
    STable: typeof import('./src/components/sTable/index.vue')['default']
  }
}
